### ISSUE TITLE
Error when trying to generate mapping from PostgreSQL "Save mapping failed"

### ISSUE THREAD

**Issue by kiavalos** [neo4j-contrib/neo4j-etl#56]
I am trying to use Neo4j ETL (vs 1.4.1) to import some data from PostgreSQL(vs 4.13). ETL is installed as part of Neo4j Desktop and it successfully connects to PostgreSQL. But when it attempts to generate the mapping, it produces an error: "Save mapping failed".

Any advice?

![Save mapping failed](https://user-images.githubusercontent.com/32520937/65713426-c9e0a080-e05e-11e9-84e9-64d6c3679b02.PNG)

**Comment by conker84** [comment]
@kiavalos are you working with remote or local db?
Can you share the logs?

**Comment by smatovski** [comment]
I have the same issue but with MySQL as the RDBMS. How do I pull logs?

**Comment by jexp** [comment]
the desktop log files you can see here:

https://github.com/neo4j-apps/neo4j-desktop/wiki/FAQ#where-can-i-find-log-files
and fo the app:

- enable developer mode in desktop settings . (at the bottom)
- reload the graph app
- then you should have a button for "Developer Tools"
- and copy the content of teh javascript console from there

thanks a lot

**Comment by smatovski** [comment]
[ETL Log.log](https://github.com/neo4j-contrib/neo4j-etl/files/3684025/ETL.Log.log)
[debug.log](https://github.com/neo4j-contrib/neo4j-etl/files/3684047/debug.log)
[neo4j.log](https://github.com/neo4j-contrib/neo4j-etl/files/3684048/neo4j.log)
Here are my logs

**Comment by icsa** [comment]
The tool generates the following command line option:

--output-mapping-file "/..._mapping.json"

I.E. The tool is attempting to write the mapping to the root of the file system - for which it does not have permission. That is why the mapping cannot be saved.

Perhaps an environment variable was not initialized as the parent directory of the mapping file?

**Comment by conker84** [comment]
Hi folks,
can you try with this?
https://www.dropbox.com/s/wfk02zpo0ln6nq6/neo4j-etl-ui-1.4.0-release.tar.gz?dl=0

In order to install it provide the path where you downloaded with the `file://` prefix
<img width="604" alt="Schermata 2019-10-04 alle 12 31 48" src="https://user-images.githubusercontent.com/1833335/66201265-400a8600-e6a3-11e9-9a0f-56442fe03920.png">


Thanks a lot

**Comment by icsa** [comment]
Hi Andrea,
The DropBox link to v 1.4.0 of the ETL UI is broken.  Can you fix it so that we may download version 1.4.0?
Kevin
    On Friday, October 4, 2019, 03:34:41 a.m. PDT, Andrea Santurbano <notifications@github.com> wrote:  
 
 
Hi folks,
can you try with this?
https://www.dropbox.com/s/wfk02zpo0ln6nq6/neo4j-etl-ui-1.4.0-release.tar.gz?dl=0

In order to install it provide the path where you downloaded with the file:// prefix


Thanks a lot

**Comment by icsa** [comment]
How does one install a specific version (e.g. 1.4.0) of Neo4J ETL UI?

**Comment by conker84** [comment]
@icsa If you tried via email, yes the link generated by Dropbox was broken so I updated the post with a good one :) 
https://www.dropbox.com/s/ka5rf3j594jql3h/neo4j-etl-ui-1.4.0-release.tar.gz?dl=0
About the installation I there is an image into my comment that I guess you are not able to see via email, so please look into the web page :)
Thanks a lot
